apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: {{ .Values.pubsub.topic | quote }}
  annotations:
      cnrm.cloud.google.com/project-id: {{ .Values.gcpProjectID | quote }}
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {{ .Values.pubsub.subscription | quote }}
  annotations:
      cnrm.cloud.google.com/project-id: {{ .Values.gcpProjectID | quote }}
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 3600s
  retainAckedMessages: false
  topicRef:
    name: {{ .Values.pubsub.topic | quote }}
  # deadLetterPolicy:
  #   deadLetterTopicRef:
  #     name: pubsubsubscription-dep2-basic
