---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subscriber
  annotations:
    iam.gke.io/gcp-service-account: sa-pubsub-subscriber@{{ .Values.gcpProjectID }}.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: sa-subscriber-binding
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: sa-pubsub-subscriber
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{ .Values.gcpProjectID }}.svc.id.goog[{{ .Release.Namespace }}/subscriber]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    # cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/project-id: {{ .Values.gcpProjectID | quote }}
  name: sa-pubsub-subscriber
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-subscriber-pubsub
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubSubscription
    name: {{ .Values.pubsub.subscription | quote }}
  memberFrom:
    serviceAccountRef:
      name: sa-pubsub-subscriber
  role: roles/pubsub.subscriber
