---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: publisher
  annotations:
    iam.gke.io/gcp-service-account: sa-pubsub-publisher@{{ .Values.gcpProjectID }}.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: sa-publisher-binding
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: sa-pubsub-publisher
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{ .Values.gcpProjectID }}.svc.id.goog[{{ .Release.Namespace }}/publisher]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    # cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/project-id: {{ .Values.gcpProjectID | quote }}
  name: sa-pubsub-publisher
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-publisher-pubsub-test
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: {{ .Values.pubsub.topic | quote }}
  memberFrom:
    serviceAccountRef:
      name: sa-pubsub-publisher
  role: roles/pubsub.publisher
